name: Build OpenKey

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      configuration:
        description: 'Build Configuration'
        required: true
        default: 'Release'
        type: choice
        options:
          - Release
          - Debug
      platform:
        description: 'Build Platform'
        required: true
        default: 'x86'
        type: choice
        options:
          - x86
          - x64

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Build Solution
      run: |
        MSBuild.exe "Sources/OpenKey/win32/OpenKey/OpenKey.sln" /p:Configuration=Release /p:Platform=x64
        
    - name: Archive Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: OpenKey-Build
        path: Sources/OpenKey/win32/OpenKey/x64/Release/

